// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLym7VXjujtb-CAKN3hkCR2cd3ttF0tcc',
    appId: '1:300054922482:web:0ba81ca9091dc8e597fc6b',
    messagingSenderId: '300054922482',
    projectId: 'meapsbooks',
    authDomain: 'meapsbooks.firebaseapp.com',
    storageBucket: 'meapsbooks.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk4y4xbWeF5VlBMsOgC74Poiaj7R13-Dk',
    appId: '1:300054922482:android:beb1502113c4fdf997fc6b',
    messagingSenderId: '300054922482',
    projectId: 'meapsbooks',
    storageBucket: 'meapsbooks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDinylhM_LWS4S-o9SQwJUKns06_5osjk',
    appId: '1:300054922482:ios:262b2e170bd84c4397fc6b',
    messagingSenderId: '300054922482',
    projectId: 'meapsbooks',
    storageBucket: 'meapsbooks.appspot.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDinylhM_LWS4S-o9SQwJUKns06_5osjk',
    appId: '1:300054922482:ios:b88029ce5197da1297fc6b',
    messagingSenderId: '300054922482',
    projectId: 'meapsbooks',
    storageBucket: 'meapsbooks.appspot.com',
    iosBundleId: 'com.example.meapsbook.RunnerTests',
  );
}
